In [3]:
!pip install PyPDF2 pandas

Requirement already satisfied: PyPDF2 in c:\users\hp\anaconda3\lib\site-packages (3.0.1)
Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (1.2.4)
Requirement already satisfied: pytz>=2017.3 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: typing_extensions>=3.10.0.0 in c:\users\hp\anaconda3\lib\site-packages (from PyPDF2) (4.4.0)

In [15]:
import PyPDF2
import pandas as pd
def pdf_to_csv(pdf_file,csv_file):
    try:
        with open(pdf_file,'rb')as pdf:
            reader=PyPDF2.PdfReader(pdf)
            text_data=[]
            
            for page in reader.pages:
                text_data.append(page.extract_text())
                rows=[line.split()for page in text_data for line in page.split('\n')]
                df=pd.DataFrame(rows)
                df.to_csv(csv_file,index=False,header=False)
                print(f"PDF file'{pdf_file}' has been successfully converted to CSV '{csv_file}'")
    except Exception as e :
                    print(f"error:{e}")

In [16]:
pdf_file="Downloads/msctimetable.pdf"
csv_file="msc.csv"
pdf_to_csv(pdf_file,csv_file)

PDF file'Downloads/msctimetable.pdf' has been successfully converted to CSV 'msc.csv'
PDF file'Downloads/msctimetable.pdf' has been successfully converted to CSV 'msc.csv'
PDF file'Downloads/msctimetable.pdf' has been successfully converted to CSV 'msc.csv'

In [17]:
import PyPDF2
import pandas as pd
def pdf_to_csv(pdf_file,csv_file):
    try:
        with open(pdf_file,'rb')as pdf:
            reader=PyPDF2.PdfReader(pdf)
            text_data=[]
            
            for page in reader.pages:
                text_data.append(page.extract_text())
                rows=[line.split()for page in text_data for line in page.split('\n')]
                df=pd.DataFrame(rows)
                df.to_csv(csv_file,index=False,header=False)
                print(f"PDF file'{pdf_file}' has been successfully converted to CSV '{csv_file}'")
    except Exception as e :
                    print(f"error:{e}")

In [20]:
pdf_file="Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf"
csv_file="anithamammaterial.csv"
pdf_to_csv(pdf_file,csv_file)

PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'
PDF file'Downloads/Ver3_Full Manual_Predictive analytics Lab.pdf' has been successfully converted to CSV 'anithamammaterial.csv'

In [22]:
df=pd.read_csv("anithamammaterial.csv")

In [23]:
df.head()

,Predictive,Analytics,Lab,–,23DS470,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Dr.D.Anitha,","Dr.C.Mahadevi,",Mrs.Anitha,"Gracy,",Dept.,of,AMCS,Page,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
dc=pd.read_csv("msc.csv")
dc.head()

,THIAGARAJAR,COLLEGE,OF,"ENGINEERING,",MADURAI,–,625,015,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,(A,Govt,Aided,Autonomous,Institution,Affiliated,to,Anna,University),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LAB,TIME,TABLE,EVEN,SEMESTER,2024,-2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Department:,Applied,Mathematics,&,Computational,Science,Lab,Name:,IBM,(Data,Science),Lab,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
class
def header(self):
self.set_font('Arial', 'B', 12)
self.cell(0, 10, 'CSV to PDF Conversion', 0, 1, 'C')
def footer(self):
self.set_y(-15)
self.set_font('Arial', 'I', 8)
self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')
def csv_to_pdf(csv_file, pdf_file):
try:
df = pd.read_csv(csv_file)
pdf = PDF()
pdf.add_page()
pdf.set_font('Arial', '', 10)
col_widths = [40] * len(df.columns)
pdf.set_fill_color(200, 220, 255)
for col in df.columns:
pdf.cell(col_widths[df.columns.get_loc(col)], 10, str(col), 1, 0, 'C',
fill=True)
pdf.ln()

     for _, row in df.iterrows():
        for col in df.columns:
            df.cell(col_widths[df.columns.get_loc(col)], 10, str(row[col]), 1,0, 'C')
pdf.ln()
pdf.output(pdf_file)
print(f"CSV file '{csv_file}' has been successfully converted to PDF file'{pdf_file}'.")
   except Exception as e:
        print(f"Error: {e}")

In [ ]:
csv_file = "input.csv"
pdf_file = "output.pdf" 
csv_to_pdf(csv_file, pdf_file)